# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.23.4


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print("Memory size of one array element in bytes is %d and the size of the array is %d" % (null.itemsize, null.size))

Memory size of one array element in bytes is 8 and the size of the array is 10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_1md = np.zeros(10)
null_1md[4] = 1
print(null_1md)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr1 = np.array(range(10,50))
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
print(np.flip(arr1))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
arr2 = np.array(range(0,9)).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
arr3 = np.array([1,2,0,0,4,0])
print(np.where(arr3==0)[0])

[2 3 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
id_matrix = np.identity(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
arr4 = np.random.random((3,3))
arr4

array([[0.25635314, 0.1512175 , 0.53696929],
       [0.17212985, 0.69678492, 0.25971824],
       [0.01638488, 0.53199121, 0.03463664]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr5 = np.random.random((10,10))
print("The min value of the arr5 is %f and the max value is %f" % (arr5.min(), arr5.max()))

The min value of the arr5 is 0.011930 and the max value is 0.997127


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
arr6 = np.random.random(30)
arr6.mean()

0.4680681071507735

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr7 = np.ones((10,10))
arr7[1:9,1:9]=0
print(arr7)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
arr8 = np.random.randn(10,10)
np.pad(arr8, pad_width=1,mode='constant', constant_values=0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        , -0.18488357,  0.91629111,  0.2934068 ,  1.93287495,
        -0.87265715, -0.27751946, -2.61692489, -0.30644288,  0.53861356,
         1.53123619,  0.        ],
       [ 0.        , -0.32890228, -0.92389338, -3.01244248, -1.58639638,
         0.24933999, -0.92837947, -0.67895114,  2.23425398,  0.55359861,
         1.03841552,  0.        ],
       [ 0.        ,  1.54151093, -0.37222402,  0.7228261 ,  0.57646744,
         0.86933795, -0.47666754, -0.16722556,  1.16912524, -0.16327456,
        -0.80568502,  0.        ],
       [ 0.        , -1.70780228,  1.47195514, -1.16357995,  0.94030783,
         0.16671619, -0.15773471, -0.72574623,  0.17425664, -0.49864191,
         2.94946427,  0.        ],
       [ 0.        , -0.99919551,  0.13398258,  1.32382349,  1.21490633,
        -1.50647455, -

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print('0 * np.nan = ', 0 * np.nan)
print('np.nan == np.nan = ', np.nan == np.nan)
print('np.inf > np.nan = ', np.inf > np.nan)
print('np.nan - np.nan = ', np.nan - np.nan)
print('np.nan in set([np.nan]) = ', np.nan in set([np.nan]))
print('0.3 == 3 * 0.1 = ', 0.3 == 3 * 0.1)

0 * np.nan =  nan
np.nan == np.nan =  False
np.inf > np.nan =  False
np.nan - np.nan =  nan
np.nan in set([np.nan]) =  True
0.3 == 3 * 0.1 =  False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag(1+np.arange(0,4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
arr9 = np.zeros((8,8))
arr9[1::2,::2] = 1
arr9[::2,1::2] = 1
print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
## Info for np.tile functioning
# np.info(np.tile)

arr11 = np.array([[1,0],[0,1]])
np.tile(arr11,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
arr12 = np.random.randint(low = 1, high = 100, size = (5,5))
arr12 = (arr12 - arr12.min())/(arr12.max() - arr12.min())
print(arr12)

[[0.13402062 0.83505155 0.16494845 0.         0.20618557]
 [0.28865979 0.04123711 0.31958763 1.         0.62886598]
 [0.80412371 0.56701031 0.80412371 0.42268041 0.90721649]
 [0.70103093 0.96907216 0.4742268  0.36082474 0.73195876]
 [0.64948454 0.39175258 0.22680412 0.44329897 0.84536082]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
arr13, arr14 = np.random.random((5,3)), np.random.random((3,2))
## Result of the dot product is a 5x2 matrix
np.dot(arr13,arr14) # == arr13 @ arr14

array([[0.42251997, 0.59345227],
       [0.84143748, 0.84544647],
       [0.38966358, 0.49914379],
       [0.36251258, 0.26519787],
       [0.89428551, 0.98746678]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [37]:
arr15 = np.array(range(0,20))
print(arr15)
arr15[4:8] *=-1
print(arr15)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [51]:
print(sum(range(5), -1))

## The following code imports all the functions of numpy.
## The function "range" doesn't exist in numpy. The function is called "arange".
## Therefore, the code should return an error
# from numpy import *
# print(sum(range(5),-1))

## This is the proper call to the numpy function
print(sum(np.arange(5),-1))

9
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [94]:
Z = np.random.randint(low=1, high=20,size=10)
print("Z = %s" % Z)
print("Z**Z is %s" % str(Z**Z).strip())
print("2<<Z>>2 = %s " % (2<<Z>>2))
print("Z<-Z =", Z<-Z)
# print(1j*Z) not legal
print("Z/1/1",Z/1/1)
# print(Z<Z>Z) not legal

Z = [15  7 17 15  6  3 15 10  8 14]
Z**Z is [  437893890380859375               823543 -2863221430593058543
   437893890380859375                46656                   27
   437893890380859375          10000000000             16777216
    11112006825558016]
2<<Z>>2 = [16384    64 65536 16384    32     4 16384   512   128  8192] 
Z<-Z = [False False False False False False False False False False]
Z/1/1 [15.  7. 17. 15.  6.  3. 15. 10.  8. 14.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [102]:
print(np.array(0) / np.array(0)) # invalid value encountered
print(np.array(0) // np.array(0)) # divide by zero ecountered
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_60203/2283366505.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) # invalid value encountered
/tmp/ipykernel_60203/2283366505.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) # divide by zero ecountered


#### 29. How to round away from zero a float array ? (★☆☆)

In [121]:
arr16 = np.array(np.arange(0,5,.1))
print(arr16)

## Two methods
print(arr16.astype(int))
# Or
print(arr16.round(0))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3
 3 3 3 4 4 4 4 4 4 4 4 4 4]
[0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 5. 5.
 5. 5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [131]:
print(arr15, arr16, sep = "\n")
print(np.intersect1d(arr15,arr16))

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
[0. 1. 2. 3.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [139]:
np.seterr(all="ignore")
## For example this code doesn't show RuntimeWarnings
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))

nan
0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [142]:
## numpy.emath.sqrt automatically handles negative inputs to sqrt, whereas numpy.sqrt return a complex result
print("np.sqrt(-1) == np.emath.sqrt(-1) is", np.sqrt(-1) == np.emath.sqrt(-1), " because: \n")
print("np.sqrt(-1) = ", np.sqrt(-1), " and np.emath.sqrt(-1) = ", np.emath.sqrt(-1))

np.sqrt(-1) == np.emath.sqrt(-1) is False  because: 

np.sqrt(-1) =  nan  and np.emath.sqrt(-1) =  1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

See [Numpy guide: Datetimes & Timedeltas](https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [175]:
print(np.datetime64("today") - np.timedelta64(24,'h'), np.datetime64("today"), np.datetime64("today")+ np.timedelta64(24,"h"))

2022-12-14T00 2022-12-15 2022-12-16T00


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [178]:
print(np.arange(np.datetime64('2016-07-01'),np.datetime64('2016-08-01')))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [200]:
## It's possible to execute the computation on a transposed matrix
A, B = np.array(range(0,8)), np.array(range(0,8))
A_T, B_T = np.transpose(A), np.transpose(B)
print((A_T+B_T)*(-A_T/2))

[  0.  -1.  -4.  -9. -16. -25. -36. -49.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)